# Generated by Django 4.2.9 on 2024-07-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
            ],
        ),
    ]
