# Generated by Django 4.2.9 on 2024-07-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveInvoice',
            fields=[
            ],
        ),
    ]
