# Generated by Django 4.2.9 on 2024-07-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_archiveinvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveInvoice',
        ),
    ]
